name: Run Stock Screener

on:
  schedule:
    # Runs every 15 minutes
    - cron: '*/15 * * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-screener-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy requests sqlalchemy psycopg2-binary

      - name: Run the stock screener script
        env:
          # This securely uses the secret you created
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python GuruLedgerCoreScript.py # IMPORTANT: Change this to your script's filename
